epochs: 100
gpus: 1
load: False
data:
  batch_size: 5
  dataset: "data/"
  seed: 69420
  nfiles: 100
  half_prec: True
  p: 0.0 # dropout

opt:
  lr: 0.001
  b1: 0.9
  b2: 0.99

mod:
  M: 625
  N: 2137
  hidden_layers: [32, 16]
  latent: 2

es:
  patience: 20
  min_delta: 0.005
