epochs: 50
gpus: 4
data:
  batch_size: 256
  dataset: "data/"
  seed: 2531
  nfiles: 20480
  half_prec: True
  num_workers: 8

opt:
  lr: 0.0025
  b1: 0.9
  b2: 0.99
  loss_scaler: 1.0

mod:
  M: 625
  N: 2137
  hidden_layers: [512, 256]
  latent: 32
  p: 0.0 # dropout

es:
  patience: 20
  min_delta: 0.005
