epochs: 50
gpus: 4
load: False
data:
  batch_size: 128
  dataset: "data/"
  seed: 42069
  nfiles: 25600
  half_prec: True
  num_workers: 4

opt:
  lr: 0.001
  b1: 0.9
  b2: 0.99

mod:
  M: 625
  N: 2137
  hidden_layers: [1024, 512, 128]
  latent: 32
  kld_weight: 0.00025
  p: 0.0 # dropout
  beta: 4
  loss_type: "H"

es:
  patience: 10
  min_delta: 0.005
