epochs: 50
gpus: 4
load: False
data:
  batch_size: 32
  seed: 42069
  nfiles: 25600
  half_prec: True
  num_workers: 4

opt:
  lr: 0.001
  b1: 0.9
  b2: 0.99

mod:
  M: 625
  N: 2137
  hidden: [1, 16, 8, 8]
  p: 0.0 # dropout
  beta: 4
  loss_type: "H"

es:
  patience: 5
  min_delta: 0.005

