epochs: 5
gpus: 4 
data:
  batch_size: 32
  dataset: "data/"
  val_split: 0.2
  seed: 1337 
  nfiles: 25600
  half_prec: True
  num_workers: 4
  shuffle: True

opt:
  lr: 0.001 
  b1: 0.9
  b2: 0.99
  loss_scaler: 1.0
  patience: 5
  factor: 0.5
  loss_scale: 32.0

mod:
  M: 625
  N: 2137
  hidden: [1, 32, 64]
  latent: 128
  p: 0.0 

es:
  patience: 10
  min_delta: 0.01

ad:
  percentile: 95
