epochs: 100
gpus: 4
load: False
data:
  dataset: "data/"
  batch_size: 64
  val_split: 0.2
  seed: 1337
  nfiles: 25600
  half_prec: True
  num_workers: 4

opt:
  lr: 0.0001
  b1: 0.9
  b2: 0.99

mod:
  M: 625
  N: 2137
  hidden: [1, 16, 8, 8]
  p: 0.0 # dropout
  beta: 4
  loss_type: "H"

es:
  patience: 20
  min_delta: 0.000001

