epochs: 3
gpus: 4
data:
  batch_size: 20
  dataset: "data/"
  val_split: 0.2
  seed: 1337 
  nfiles: 200
  half_prec: True
  num_workers: 4
  shuffle: True

opt:
  lr: 0.0000001 # 1e-8
  b1: 0.9
  b2: 0.999
  patience: 5
  lr_scheduler: 'reduce'
  threshold: 0.001
  factor: 0.5
  loss_scale: 1.0

mod:
  M: 625
  N: 2137
  hidden: [16, 32, 64]
  latent: 128
  kld_weight: 0.01
  p: 0.0  # dropout

es:
  patience: 10
  min_delta: 0.001

ad:
  percentile: 95

es:
  patience: 10
  min_delta: 0.000001

