epochs: 200
gpus: 4
data:
  batch_size: 32
  dataset: "data/"
  val_split: 0.2
  seed: 1337 
  nfiles: 25600
  half_prec: False
  num_workers: 4
  shuffle: True

opt:
  lr: 0.0005 
  b1: 0.9
  b2: 0.999
  patience: 5
  lr_scheduler: 'reduce'
  threshold: 0.001
  factor: 0.5
  loss_scale: 1.0

mod:
  M: 625
  N: 2137
  hidden: [16, 32, 64, 128]
  latent: 128
  kld_weight: 0.01
  beta: 4.0
  p: 0.0  # dropout

es:
  patience: 10
  min_delta: 0.001

ad:
  percentile: 95

es:
  patience: 100
  min_delta: 0.01