epochs: 5
gpus: 1
load: False
data:
  batch_size: 4
  dataset: "data/"
  seed: 42069
  nfiles: 16
  half_prec: True
  num_workers: 2

opt:
  lr: 0.0042
  b1: 0.9
  b2: 0.99

mod:
  M: 625
  N: 2137
  hidden_layers: [128, 64]
  latent: 32
  kld_weight: 1.0 # 0.00025
  p: 0.0 # dropout

es:
  patience: 3
  min_delta: 0.005
