epochs: 100
gpus: 4 
data:
  batch_size: 20
  dataset: "data/"
  val_split: 0.2
  seed: 1337 
  nfiles: 400
  half_prec: False
  num_workers: 4
  shuffle: True

opt:
  lr: 0.001
  b1: 0.9
  b2: 0.99
  lr_scheduler: 'reduce'
  threshold: 0.1
  patience: 5
  factor: 0.5
  loss_scale: 1.0
  beta: 4.0 # 0.01

mod:
  M: 625
  N: 2137
  hidden: [1024, 256]
  latent: 128
  kld_weight: 0.1  #0.01
  p: 0.0 # dropout

es:
  patience: 10
  min_delta: 0.1

ad:
  percentile: 95

#p: 0.0 # dropout
