epochs: 20  # Increased number of epochs
gpus: 4 
data:
  batch_size: 20 # Increased batch size
  dataset: "data/"
  val_split: 0.2
  seed: 1337 
  nfiles: 200
  half_prec: False
  num_workers: 4
  shuffle: True

opt:
  lr: 0.0001
  b1: 0.9
  b2: 0.999 
  lr_scheduler: 'reduce'
  threshold: 0.001
  patience: 5 
  factor: 0.5
  loss_scale: 1.0

mod:
  M: 625
  N: 2137
  hidden: [1024, 512] 
  latent: 256
  kld_weight: 0.001
  beta: 0.0001
  p: 0.1  

es:
  patience: 10  
  min_delta: 0.0001  

ad:
  percentile: 95

#p: 0.0 # dropout
