epochs: 5 #100
gpus: 4 # 4
data:
  batch_size: 32 # 32
  dataset: "data/"
  val_split: 0.2
  seed: 1337 
  nfiles: 2560
  half_prec: True
  num_workers: 4
  shuffle: True

opt:
  lr: 0.00000001 # 1e-8
  b1: 0.9
  b2: 0.99
  loss_scaler: 1.0
  patience: 5
  factor: 0.5
  loss_scale: 1.0

mod:
  M: 625
  N: 2137
  hidden: [512]
  latent: 128
  kld_weight: 0.01
  p: 0.0 # dropout

es:
  patience: 10
  min_delta: 0.00001

ad:
  percentile: 95

#p: 0.0 # dropout
